### ISSUE TITLE
Kanban board: Setup

### ISSUE THREAD

**Issue by Ismailco** [daudi13/space-travel#13]
For this capstone, we are a team of 2 developers.

@daudi13 
@Ismailco

Here is the link to the [kanban board](https://github.com/daudi13/space-travel/projects/1)

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Ismailco and @daudi13,

Good job so far!
✔️ Kanban is well set up
✔️ Tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] You should have 17 tasks, but you currently have only 16. Kindly add the missing card here:

  ![daudi-join](https://user-images.githubusercontent.com/36542986/162711907-5f630f69-d4af-4135-82ef-43bb6ce5ea8e.jpg)

- [x] Remember to assign the task to a member 

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elyor-doniyorov** [comment]
Hi @Ismailco and @daudi13, 

In my opinion, your Kanban board is ready to use!  There is nothing else to say other than... well done :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
